Issue 14
santibatte/dpa_2021 pull request #35
Opened 2021-02-23 08:47 UTC by codeMariana

2021-02-23 23:02 UTC, Roberto919 commented on README.md
> +#### Pipeline
Esta parte se ve bastante bien, solo creo que hay que agregar las siguientes instrucciones:
1. Agregar archivo con credenciales en carpeta local/conf
2. Tener activo un bucket de s3 con el nombre Xxx

2021-02-23 23:03 UTC, Roberto919 requested changes
Lo veo chido, solo creo que hay que agregar un par de cositas más en la sección de pipeline (agregué comentario en el código)

2021-02-24 01:39 UTC, codeMariana commented on README.md
> +#### Pipeline
Listo, podrías echarle un ojo @Roberto919

2021-02-24 02:28 UTC, Roberto919 approved these changes
Super!! Ya lo veo perfecto <3

2021-02-24 02:28 UTC, merged